import React from 'react';

const Home = () => {
  return (
    <div style={{ padding: '2rem' }}>
      <h2>Welcome to your MERN Stack Application</h2>
      <p>This is a modular folder structure generated by your CLI.</p>
    </div>
  );
};

export default Home;
